// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeFile(path string) (*App, func(), error) {
	file, cleanup, err := OpenFile(path)
	if err != nil {
		return nil, nil, err
	}
	content, cleanup2, err := Clean()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := &App{
		File:    file,
		Cleanup: content,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
