// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greet := NewGreet(message)
	event, err := NewEvent(greet)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
