// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeMessage(phrase string, code int) Message {
	message := _wireMessageValue
	return message
}

var (
	_wireMessageValue = Message{
		Message: "msg",
	}
)
